#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:20:00

module load singularity

rm -r images
rm -r images.json

singularity run -e /N/u/brlife/Carbonate/plot3dsurfaces-2017-11-15-4a6c5a3759e0.img

if [ ! -s images.json ];
then 
	echo "images.json missing"
	exit 1
fi
